version: '3'
services:
  app:
    ports:
      - "85:8000"
    restart: always
    command: [ bash, entrypoint.sh ]
    build:
      context: .
      args:
        USERNAME: $USER
    volumes:
      - .:/app
    depends_on:
      - postgresql
    networks:
      - db_network
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 